# Generated by Django 4.1.4 on 2023-01-31 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0030_remove_institucion_id_comuna_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucionn',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('descripcion_institucion', models.CharField(max_length=100)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional_salud',
            fields=[
                ('id_profesional_salud', models.AutoField(primary_key=True, serialize=False)),
                ('rut_profesional_salud', models.CharField(max_length=100)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico_y_enfermera.institucionn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
