# Generated by Django 4.1.4 on 2023-01-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico_y_enfermera', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institucionn',
            new_name='Institucion',
        ),
    ]
