# Generated by Django 4.1.4 on 2023-01-31 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_rename_app_tipo_terapiaa_app_tipo_terapia_and_more'),
        ('medico_y_enfermera', '0002_rename_institucionn_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional_paciente',
            fields=[
                ('id_profesional_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('id_profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico_y_enfermera.profesional_salud')),
            ],
        ),
    ]
