# Generated by Django 4.1.4 on 2023-02-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_y_enfermera', '0003_profesional_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_enfermera_paciente',
            fields=[
                ('id_app_enfermera_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('username_enfermera', models.CharField(max_length=100)),
                ('username_paciente', models.CharField(max_length=100)),
            ],
        ),
    ]
