# Generated by Django 4.1.4 on 2023-02-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_y_enfermera', '0004_app_enfermera_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id_enfermera', models.AutoField(primary_key=True, serialize=False)),
                ('rut_enfermera', models.CharField(max_length=100)),
                ('nombre_enfermera', models.CharField(max_length=100)),
                ('apellido_enfermera', models.CharField(max_length=100)),
                ('direccion_enfermera', models.CharField(max_length=100)),
                ('correo_enfermera', models.CharField(max_length=100)),
                ('telefono_enfermera', models.CharField(max_length=100)),
                ('whatsapp_enfermera', models.CharField(max_length=100)),
                ('telegram_enfermera', models.CharField(max_length=100)),
                ('celular_enfermera', models.CharField(max_length=100)),
            ],
        ),
    ]
