# Generated by Django 4.1.4 on 2023-02-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_y_enfermera', '0005_enfermera'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_enfermera_neurologo',
            fields=[
                ('id_app_enfermera_neurologo', models.AutoField(primary_key=True, serialize=False)),
                ('username_enfermera', models.CharField(max_length=100)),
                ('username_neurologo', models.CharField(max_length=100)),
            ],
        ),
    ]
