# Generated by Django 4.1.4 on 2023-01-31 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientee',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_paciente', models.CharField(max_length=100)),
                ('telegram_paciente', models.CharField(max_length=100)),
                ('diabetes_id', models.CharField(max_length=100)),
                ('hipertension', models.CharField(max_length=100)),
                ('paciente_familiar', models.CharField(max_length=100)),
                ('whatsapp_paciente', models.CharField(max_length=100)),
                ('celular_paciente', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
