# Generated by Django 4.1.4 on 2023-01-31 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0002_pacientee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacientee',
            new_name='Paciente',
        ),
    ]
