# Generated by Django 4.1.4 on 2023-01-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_rename_pacientee_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente_documento',
            fields=[
                ('id_paciente_documento', models.AutoField(primary_key=True, serialize=False)),
                ('autorizado', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('documento_id', models.CharField(max_length=100)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
