# Generated by Django 4.1.4 on 2023-01-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_tipo_terapiaa',
            fields=[
                ('id_app_tipo_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
