# Generated by Django 4.1.4 on 2023-01-31 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_app_tipo_terapiaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapiaa',
            fields=[
                ('id_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('horarios', models.CharField(max_length=100)),
                ('fonoaudiologo_id', models.CharField(max_length=100)),
                ('paciente_id', models.CharField(max_length=100)),
                ('id_app_tipo_terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.app_tipo_terapiaa')),
            ],
        ),
    ]
