# Generated by Django 4.1.4 on 2023-01-31 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_terapiaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio_terapia',
            fields=[
                ('id_recordatorio_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('hora_recordatorio', models.CharField(max_length=100)),
                ('receta_id', models.CharField(max_length=100)),
                ('id_terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.terapiaa')),
            ],
        ),
    ]
