# Generated by Django 4.1.4 on 2023-01-31 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_recordatorio_terapia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intensidad',
            fields=[
                ('id_intensidad', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_archivo_intensidad', models.CharField(max_length=100)),
                ('intensidad', models.CharField(max_length=100)),
                ('mindb', models.CharField(max_length=100)),
                ('maxdb', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=100)),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
