# Generated by Django 4.1.4 on 2023-02-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_parentescoo',
            fields=[
                ('id_tipo_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=100)),
            ],
        ),
    ]
