# Generated by Django 4.1.4 on 2023-02-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_familiar_paciente_parentesco_and_more'),
        ('paciente', '0011_tipo_parentescoo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_parentescoo',
            new_name='Tipo_parentesco',
        ),
    ]
