# Generated by Django 4.1.4 on 2023-01-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id_trivia', models.AutoField(primary_key=True, serialize=False)),
                ('ordinal', models.CharField(max_length=100)),
                ('pregunta_trivia', models.CharField(max_length=100)),
                ('respuestas_trivias', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
