# Generated by Django 4.1.4 on 2022-12-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_telegram',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
