# Generated by Django 4.1.4 on 2023-02-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0002_regiones_delete_region'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipologias.regiones'),
        ),
    ]
