# Generated by Django 4.1.4 on 2023-01-03 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id_trivia', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta_trivia', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Trivia',
            fields=[
                ('id_respuesta_trivia', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('respuesta_trivia', models.CharField(max_length=100)),
                ('id_trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trivia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
