# Generated by Django 4.1.4 on 2023-01-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trivia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='respuestas_trivias',
            new_name='respuesta_trivia',
        ),
    ]
