# Generated by Django 4.1.4 on 2023-02-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_provincia_id_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
    ]
