# Generated by Django 4.1.4 on 2022-12-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usuario_id_tipo_usuario_usuario_telefono_and_more'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='usuario',
            name='Tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario'),
            preserve_default=False,
        ),
    ]
