# Generated by Django 4.1.4 on 2022-12-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usuario_telefono_usuario_tipo_usuario'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='usuario',
            name='Tipo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario'),
        ),
    ]
