# Generated by Django 4.1.4 on 2023-01-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.RenameField(
            model_name='trivia',
            old_name='descripcion',
            new_name='ordinal',
        ),
    ]
