# Generated by Django 4.1.4 on 2023-01-11 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_respuestas_trivias_trivia_respuesta_trivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
