# Generated by Django 4.0.4 on 2022-12-21 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_juego',
            fields=[
                ('id_tipo_juego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_juego', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_juego',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado_1', models.CharField(max_length=100)),
                ('resultado_2', models.CharField(max_length=100)),
                ('resultado_3', models.CharField(max_length=100)),
                ('resultado_4', models.DateTimeField(auto_now_add=True)),
                ('resultado_5', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_tipo_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_juego')),
            ],
        ),
    ]
