# Generated by Django 4.0.4 on 2022-12-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipo_juego_resultado_juego_juego'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
