# Generated by Django 4.1.4 on 2023-01-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_movie_rename_descripcion_trivia_ordinal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta_trivia',
            old_name='id_trivia',
            new_name='id_pregunta',
        ),
    ]
