# Generated by Django 4.0.4 on 2022-12-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado_juego',
            name='id_juego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.juego'),
        ),
    ]
