# Generated by Django 4.0.4 on 2022-12-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resultado_juego_id_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado_juego',
            name='resultado_5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
