# Generated by Django 4.0.4 on 2022-12-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_resultado_juego_resultado_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado_juego',
            name='resultado_5',
        ),
    ]
