# Generated by Django 4.1.4 on 2023-01-20 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sopa_letras_direction_sopa_letras_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia_sopa_letras',
            fields=[
                ('id_trivia_sopa', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
