# Generated by Django 4.1.4 on 2023-01-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_trivia_sopa_letras'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopa_letras',
            name='pregunta_sopa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
