# Generated by Django 4.1.4 on 2023-01-24 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sopa_letras_pregunta_sopa'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_documento',
            fields=[
                ('id_app_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('qr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='App_enfermera_neurologo',
            fields=[
                ('id_app_enfermera_neurologo', models.AutoField(primary_key=True, serialize=False)),
                ('username_enfermera', models.CharField(max_length=100)),
                ('username_neurologo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='App_enfermera_paciente',
            fields=[
                ('id_app_enfermera_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('username_enfermera', models.CharField(max_length=100)),
                ('username_paciente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='App_tipo_terapia',
            fields=[
                ('id_app_tipo_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id_audio', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_archivo_audio', models.CharField(max_length=100)),
                ('jitter_ppq5', models.CharField(max_length=100)),
                ('jitter_rap', models.CharField(max_length=100)),
                ('maximum_pitch', models.CharField(max_length=100)),
                ('error_jitter_ppq5', models.CharField(max_length=100)),
                ('error_jitter_rap', models.CharField(max_length=100)),
                ('error_maximum_pitch', models.CharField(max_length=100)),
                ('jitter_ppq5_IA', models.CharField(max_length=100)),
                ('jitter_rap_IA', models.CharField(max_length=100)),
                ('maximum_pitch_IA', models.CharField(max_length=100)),
                ('error_jitter_ppq5_IA', models.CharField(max_length=100)),
                ('error_jitter_rap_IA', models.CharField(max_length=100)),
                ('error_maximum_pitch_IA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id_diabetes', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_diabetes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('rut_familiar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar_paciente',
            fields=[
                ('id_familiar_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=100)),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.familiar')),
            ],
        ),
        migrations.CreateModel(
            name='Hipertension',
            fields=[
                ('id_hipertension', models.AutoField(primary_key=True, serialize=False)),
                ('estado_hipertension', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('descripcion_institucion', models.CharField(max_length=100)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Intensidad',
            fields=[
                ('id_intensidad', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_archivo_intensidad', models.CharField(max_length=100)),
                ('intensidad', models.CharField(max_length=100)),
                ('mindb', models.CharField(max_length=100)),
                ('maxdb', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_documento',
            fields=[
                ('id_paciente_documento', models.AutoField(primary_key=True, serialize=False)),
                ('autorizado', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('documento_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional_paciente',
            fields=[
                ('id_profesional_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional_salud',
            fields=[
                ('id_profesional_salud', models.AutoField(primary_key=True, serialize=False)),
                ('rut_profesional_salud', models.CharField(max_length=100)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio_terapia',
            fields=[
                ('id_recordatorio_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('hora_recordatorio', models.CharField(max_length=100)),
                ('receta_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('horarios', models.CharField(max_length=100)),
                ('fonoaudiologo_id', models.CharField(max_length=100)),
                ('paciente_id', models.CharField(max_length=100)),
                ('id_app_tipo_terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.app_tipo_terapia')),
            ],
        ),
        migrations.CreateModel(
            name='Vocalizacion',
            fields=[
                ('id_vocalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_archivo_vocalizacion', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('bpminute', models.CharField(max_length=100)),
                ('bpmeasure', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='apellido_paciente',
            new_name='diabetes_id',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='correo_paciente',
            new_name='hipertension',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='direccion_paciente',
            new_name='paciente_familiar',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono_paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Trivia_sopa_letras',
        ),
        migrations.AddField(
            model_name='vocalizacion',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='recordatorio_terapia',
            name='id_terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.terapia'),
        ),
        migrations.AddField(
            model_name='profesional_salud',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesional_paciente',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='profesional_paciente',
            name='id_profesional_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesional_salud'),
        ),
        migrations.AddField(
            model_name='paciente_documento',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='intensidad',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='familiar_paciente',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audio',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
    ]
