# Generated by Django 4.0.4 on 2022-12-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_resultado_juego_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado_juego',
            name='resultado_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
