# Generated by Django 4.1.4 on 2023-01-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_app_documento_app_enfermera_neurologo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_telegram',
            field=models.CharField(default='@', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=569, max_length=100, null=True),
        ),
    ]
