# Generated by Django 4.0.4 on 2022-12-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_resultado_juego_resultado_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapista',
            fields=[
                ('id_enfermera', models.AutoField(primary_key=True, serialize=False)),
                ('rut_enfermera', models.CharField(max_length=100)),
                ('nombre_enfermera', models.CharField(max_length=100)),
                ('apellido_enfermera', models.CharField(max_length=100)),
                ('direccion_enfermera', models.CharField(max_length=100)),
                ('correo_enfermera', models.CharField(max_length=100)),
                ('telefono_enfermera', models.CharField(max_length=100)),
                ('whatsapp_enfermera', models.CharField(max_length=100)),
                ('telegram_enfermera', models.CharField(max_length=100)),
                ('celular_enfermera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('issuperuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('id_telegram', models.CharField(max_length=100)),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario')),
            ],
        ),
    ]
