# Generated by Django 4.1.4 on 2023-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_usuario_direccion_alter_usuario_id_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='+569', max_length=100, null=True),
        ),
    ]
