# Generated by Django 4.1.4 on 2022-12-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_terapista_tipo_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_paciente', models.CharField(max_length=100)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('apellido_paciente', models.CharField(max_length=100)),
                ('direccion_paciente', models.CharField(max_length=100)),
                ('correo_paciente', models.CharField(max_length=100)),
                ('telefono_paciente', models.CharField(max_length=100)),
                ('whatsapp_paciente', models.CharField(max_length=100)),
                ('telegram_paciente', models.CharField(max_length=100)),
                ('celular_paciente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=100)),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
            ],
        ),
    ]
