# Generated by Django 4.1.4 on 2023-01-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopa_letras',
            old_name='user',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='trivia',
            old_name='user',
            new_name='id_usuario',
        ),
    ]
