# Generated by Django 4.1.4 on 2022-12-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_paciente_region_provincia_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='issuperuser',
        ),
    ]
