# Generated by Django 4.0.4 on 2022-12-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_usuario_is_active_remove_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='imagenes-user'),
        ),
    ]
