# Generated by Django 4.1.4 on 2023-01-31 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_id_usuario_sopa_letras_user_and_more'),
    ]

    operations = []
