# Generated by Django 4.1.4 on 2023-01-31 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_tipo_parentesco_remove_familiar_paciente_id_familiar_and_more'),
    ]

    operations = []
