# Generated by Django 4.1.4 on 2023-01-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_tipo_parentesco_remove_familiar_paciente_id_familiar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar_paciente',
        ),
    ]
