# Generated by Django 4.0.4 on 2022-12-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_galeria_imagenes_gallery'),
        ('app', '0018_alter_gallery_image'),
    ]

    operations = [
    ]
