# Generated by Django 4.0.4 on 2022-12-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20221227_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='user',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
