# Generated by Django 4.1.4 on 2023-01-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_familiar_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_parentesco',
            fields=[
                ('id_tipo_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=100)),
            ],
        ),
    ]
