# Generated by Django 4.1.4 on 2023-01-31 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_tipo_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar_paciente',
            fields=[
                ('id_familiar_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('familiar', models.ManyToManyField(related_name='Familiar', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ManyToManyField(related_name='Paciente', to=settings.AUTH_USER_MODEL)),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_parentesco')),
            ],
        ),
    ]
