# Generated by Django 4.1.4 on 2023-01-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_familiar_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diabetes',
        ),
        migrations.DeleteModel(
            name='Hipertension',
        ),
    ]
