# Generated by Django 4.0.4 on 2022-12-27 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado_juego',
            name='timestampp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
