# Generated by Django 4.0.4 on 2022-12-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_resultado_juego_timestampp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
