# Generated by Django 4.1.4 on 2023-01-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_pacientee'),
        ('app', '0022_delete_diabetes_delete_hipertension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.pacientee'),
        ),
        migrations.AlterField(
            model_name='intensidad',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.pacientee'),
        ),
        migrations.AlterField(
            model_name='paciente_documento',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.pacientee'),
        ),
        migrations.AlterField(
            model_name='profesional_paciente',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.pacientee'),
        ),
        migrations.AlterField(
            model_name='vocalizacion',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.pacientee'),
        ),
    ]
