# Generated by Django 4.1.4 on 2023-01-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_audio_id_paciente_alter_intensidad_paciente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
