# Generated by Django 4.1.4 on 2023-01-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente_documento',
        ),
    ]
