# Generated by Django 4.0.4 on 2022-12-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='User',
            new_name='user',
        ),
    ]
