# Generated by Django 4.1.4 on 2023-01-31 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_app_tipo_terapiaa'),
        ('app', '0025_delete_paciente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='id_app_tipo_terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.app_tipo_terapiaa'),
        ),
        migrations.DeleteModel(
            name='App_tipo_terapia',
        ),
    ]
