# Generated by Django 4.0.4 on 2022-12-28 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_gallery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
