# Generated by Django 4.1.4 on 2023-01-31 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_terapiaa'),
        ('app', '0026_alter_terapia_id_app_tipo_terapia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio_terapia',
            name='id_terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.terapiaa'),
        ),
        migrations.DeleteModel(
            name='Terapia',
        ),
    ]
