# Generated by Django 4.1.4 on 2023-01-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_recordatorio_terapia_id_terapia_delete_terapia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recordatorio_terapia',
        ),
    ]
