# Generated by Django 4.1.4 on 2022-12-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_memorice_usuario_delete_galeria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='count_img',
            field=models.IntegerField(null=True),
        ),
    ]
