# Generated by Django 4.1.4 on 2023-01-31 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_recordatorio_terapia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intensidad',
        ),
    ]
