# Generated by Django 4.1.4 on 2022-12-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_gallery_count_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='count_img',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
