# Generated by Django 4.0.4 on 2022-12-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_usuario_first_name_remove_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario'),
        ),
    ]
