# Generated by Django 4.1.4 on 2023-01-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_profesional_paciente_id_profesional_salud_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesional_paciente',
        ),
    ]
