# Generated by Django 4.1.4 on 2023-02-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_familiar_paciente_parentesco_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App_enfermera_paciente',
        ),
    ]
