# Generated by Django 4.1.4 on 2023-02-01 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_delete_app_enfermera_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Terapista',
        ),
    ]
