# Generated by Django 4.1.4 on 2023-02-01 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_delete_terapista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar_paciente',
        ),
    ]
