# Generated by Django 4.1.4 on 2023-02-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_delete_familiar_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App_enfermera_neurologo',
        ),
    ]
