# Generated by Django 4.1.4 on 2023-02-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_delete_app_enfermera_neurologo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sopa_letras',
        ),
    ]
