# Generated by Django 4.1.4 on 2023-02-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_delete_sopa_letras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trivia',
        ),
    ]
