# Generated by Django 4.1.4 on 2023-02-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_delete_trivia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='id_tipo_juego',
        ),
    ]
