# Generated by Django 4.1.4 on 2023-02-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_juego'),
        ('app', '0041_remove_juego_id_tipo_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado_juego',
            name='id_juego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.juego'),
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
