# Generated by Django 4.1.4 on 2023-02-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_resultado_juego_id_juego_delete_juego'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado_juego',
        ),
    ]
