# Generated by Django 4.1.4 on 2023-02-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
