# Generated by Django 4.1.4 on 2023-02-01 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sopa_letra',
            fields=[
                ('id_sopa', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta_sopa', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
