# Generated by Django 4.1.4 on 2023-02-01 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id_trivia', models.AutoField(primary_key=True, serialize=False)),
                ('ordinal', models.CharField(max_length=100)),
                ('pregunta_trivia', models.CharField(max_length=100)),
                ('respuesta_trivia', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
