# Generated by Django 4.1.4 on 2023-02-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_juego_id_tipo_juego'),
        ('juegos', '0002_trivia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_tipo_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_juego')),
            ],
        ),
    ]
