# Generated by Django 4.1.4 on 2023-02-01 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juegos', '0003_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado_juego',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado_1', models.CharField(max_length=100)),
                ('resultado_2', models.CharField(max_length=100)),
                ('resultado_3', models.CharField(max_length=100)),
                ('resultado_4', models.CharField(blank=True, max_length=100, null=True)),
                ('resultado_5', models.CharField(blank=True, max_length=100, null=True)),
                ('timestampp', models.DateTimeField(auto_now_add=True)),
                ('id_juego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.juego')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
